name: Image Push Workflow
on:
  push:
    branches:
    - main
jobs:
  build_and_push:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      HTTP_PROXY: http://proxy-server:2222
      HTTPS_PROXY: http://proxy-server:2222
      NO_PROXY: github.com,api.github.com
      XDG_RUNTIME_DIR: /var/test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build image
      run: docker build -t my_image_2:latest .
    - name: Scan image
      id: scan
      uses: onmyquest/scan-action@master
      with:
        image-tag: my_image_2:latest
        sysdig-secure-token: 1293902d-2376-4ec4-af64-c4605434fb0e
        sysdig-secure-url: https://secure.sysdig.com
    - name: Push image
      run: docker image inspect my_image_2:latest
      #- name: Approval
      #  id: approval
      #  uses: repo/approvals-action@v2
      #  with:
      #    approval_title: Approve Image Push
      #    approval_message: Please review and approve the image push to the registry
      #- name: Push image
      #  if: steps.approval.outputs.approved == 'true'
      #  run: docker push my_image:latest
